### Content Based Filtering

### 목적 : 영화마다 코사인 유사도를 구하기 위한 작업임

    - 숫자로 바꾸는 작업

In [1]:
import pandas as pd

movies = pd.read_csv('./datasets/tmdb_5000_movies.csv')
movies.head()

C:\Users\User\AppData\Local\Temp\ipykernel_15956\4051038639.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
3  [{"name": "Legendary Pictures", "id": 923}, {"...   
4        [{"name": "Walt Disney Pictures", "id": 2}]   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26   880674609   
3  [{"iso_3166_1": "US", "name": "United States o...   2012-07-16  1084939099   
4  [{"iso_3166_1": "US", "name": "United States o...   2012-03-07   284139100   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3    165.0           [{"iso_639_1": "en", "name": "English"}]  Released   
4    132.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500  
2                                   Spectre           6.3        4466  
3                     The Dark Knight Rises           7.6        9106  
4                               John Carter           6.1        2124

In [2]:
import ast
ast.literal_eval(movies['genres'][0]) # name인 장르만 가져오기 위해 확인하고 {하나씩} 아래 함수에 넣어줌

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [3]:
def value_import(x):
    return [i['name'] for i in ast.literal_eval(x)]
movies['genres'] = movies['genres'].apply(value_import)
movies['keywords'] = movies['keywords'].apply(value_import)

In [11]:
movies['genres'][0]

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [12]:
movies['keywords'][0]

['culture clash',
 'future',
 'space war',
 'space colony',
 'society',
 'space travel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alien planet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'love affair',
 'anti war',
 'power relations',
 'mind and soul',
 '3d']

    - 장르와 키워드 기반으로 유사한 걸 뽑기 위해 가져온거임

In [14]:
# 장르와 키워드를 합치기
# soup이라는 컬럼에 넣어주기
movies['soup'] = movies['genres'] + movies['keywords']

In [13]:
movies.head()

budget                                         genres  \
0  237000000  [Action, Adventure, Fantasy, Science Fiction]   
1  300000000                   [Adventure, Fantasy, Action]   
2  245000000                     [Action, Adventure, Crime]   
3  250000000               [Action, Crime, Drama, Thriller]   
4  260000000           [Action, Adventure, Science Fiction]   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [culture clash, future, space war, space colon...                en   
1  [ocean, drug abuse, exotic island, east india ...                en   
2  [spy, based on novel, secret agent, sequel, mi...                en   
3  [dc comics, crime fighter, terrorist, secret i...                en   
4  [based on novel, mars, medallion, space travel...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  ...     revenue runtime  \
0  [{"name": "Ingenious Film Partners", "id": 289...  ...  2787965087   162.0   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...  ...   961000000   169.0   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...  ...   880674609   148.0   
3  [{"name": "Legendary Pictures", "id": 923}, {"...  ...  1084939099   165.0   
4        [{"name": "Walt Disney Pictures", "id": 2}]  ...   284139100   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                soup  \
0  [Action, Adventure, Fantasy, Science Fiction, ...   
1  [Adventure, Fantasy, Action, ocean, drug abuse...   
2  [Action, Adventure, Crime, spy, based on novel...   
3  [Action, Crime, Drama, Thriller, dc comics, cr...   
4  [Action, Adventure, Science Fiction, based on ...   

                                        soup_literal  
0  Action Adventure Fantasy Science Fiction cultu...  
1  Adventure Fantasy Action ocean drug abuse exot...  
2  

In [15]:
movies['soup']

0       [Action, Adventure, Fantasy, Science Fiction, ...
1       [Adventure, Fantasy, Action, ocean, drug abuse...
2       [Action, Adventure, Crime, spy, based on novel...
3       [Action, Crime, Drama, Thriller, dc comics, cr...
4       [Action, Adventure, Science Fiction, based on ...
                              ...                        
4798    [Action, Crime, Thriller, united states–mexico...
4799                                    [Comedy, Romance]
4800    [Comedy, Drama, Romance, TV Movie, date, love ...
4801                                                   []
4802    [Documentary, obsession, camcorder, crush, dre...
Name: soup, Length: 4803, dtype: object

    - 콤마(,), 리스트를 없애야함

In [16]:
def join_words(x):
    return (' ').join(x)

movies['soup_literal'] = movies['soup'].apply(join_words)

In [17]:
movies['soup_literal'][0]

'Action Adventure Fantasy Science Fiction culture clash future space war space colony society space travel futuristic romance space alien tribe alien planet cgi marine soldier battle love affair anti war power relations mind and soul 3d'

    - 이제 숫자로 바꿀거임
    - 방법은 Count, TF-IDF가 있음
    - count : 카운트 기반 벡터화, 중요한 의미가 없는 것도 빈도수가 많으면 중요하게 본다는 단점이 있음
    - TF-IDF 벡터화 : 위 단점을 극복한것임. ex_ 신문기사, 일기 등

## sklearn.feature_extraction.text.CountVectorize
- class sklearn.feature_extraction.text.CountVectorizer(*, input='content', encoding='utf-8', decode_error='strict', strip_accents=None, lowercase=True, preprocessor=None, tokenizer=None, stop_words=None, token_pattern='(?u)\b\w\w+\b', ngram_range=(1, 1), analyzer='word', max_df=1.0, min_df=1, max_features=None, vocabulary=None, binary=False, dtype=<class 'numpy.int64'>)

In [18]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

count_vector = CountVectorizer()
soup_mat = count_vector.fit_transform(movies['soup_literal'])

In [20]:
soup_mat.shape # 7164개인 벡터로 만들어진거임

(4803, 7164)

    - 각 영화마다 코사인 유사도(cosine_similarity)를 구할거임
    - 라이브러리 안에 있음

### sklearn.metrics.pairwise.cosine_similarity
- sklearn.metrics.pairwise.cosine_similarity(X, Y=None, dense_output=True)

In [22]:
from sklearn.metrics.pairwise import cosine_similarity

soup_similarity = cosine_similarity(soup_mat, soup_mat)

In [25]:
soup_similarity[0]

array([1.        , 0.10482848, 0.06537205, ..., 0.07161149, 0.        ,
       0.        ])

    - 유사도를 구했으니
    - soup_similarity(유사도)를 영화ID를 기준으로 내림차순 하기

In [26]:
soup_sim_sorted_ind = soup_similarity.argsort()[:, ::-1] # 내림차순 정렬하는 방법임
# argsort()는 큰 것부터 인덱스 번호를 찍어줌
soup_sim_sorted_ind # 유사도가 큰 거의 자리를 알려주는 거임. 몇번쨰 있는지지

array([[   0,  278,  541, ..., 2833, 2830, 2401],
       [   1,   12,  199, ..., 2847, 2845, 2401],
       [   2,   11,  147, ..., 2985, 2983, 2401],
       ...,
       [4800, 3809, 3264, ..., 2198, 2200, 2401],
       [4802, 1594, 1596, ..., 3204, 3205,    0],
       [4802, 4431, 3503, ..., 3105, 3104,    0]], dtype=int64)

    - 다른 방법 NearestNeighbors를 사용해서 유사도를 구할거임

### sklearn.neighbors.NearestNeighbors
- class sklearn.neighbors.NearestNeighbors(*, n_neighbors=5, radius=1.0, algorithm='auto', leaf_size=30, metric='minkowski', p=2, metric_params=None, n_jobs=None)
    - n_neighbors=5 가장 가까운 5개를 찾아줌
    - metric='minkowski' 어떤 거리? 우리는 코사인!

In [27]:
# NearestNeighbors 를 활용한 유사도
from sklearn.neighbors import NearestNeighbors

model_knn = NearestNeighbors(n_neighbors=20, metric='cosine')
model_knn.fit(soup_mat)

NearestNeighbors(metric='cosine', n_neighbors=20)

    - NearestNeighbors안에 있는 메소드(kneighbors) 사용
    - kneighbors([X, n_neighbors]) : 지정한 것(X)에서 몇개(n_neighbors)찾아줌

In [29]:
similariity, indices_result = model_knn.kneighbors(soup_mat[1], n_neighbors=11)

In [31]:
indices_result[0][1: ] # 자기자신을 제외한 것만 보기

array([  12,  199,  340,   71, 2836,   17,   30,  115,    5, 2655],
      dtype=int64)

In [32]:
movies['original_title'][indices_result[0][1:]] # 영화 이름 확인

12             Pirates of the Caribbean: Dead Man's Chest
199     Pirates of the Caribbean: The Curse of the Bla...
340                                      Cutthroat Island
71                  The Mummy: Tomb of the Dragon Emperor
2836                                                Frida
17            Pirates of the Caribbean: On Stranger Tides
30                                           Spider-Man 2
115                                               Hancock
5                                            Spider-Man 3
2655          Dungeons & Dragons: Wrath of the Dragon God
Name: original_title, dtype: object